spring:
  profiles:
    active: ${profile}   # java -jar shoppingapp.jar --profile=prod


# Server Configuration
server:
  port: 8080


# JWT secret
app:
  domain: localhost
  base_url: /api/v1
  jwt:
    secret: ${jwt.secret}
    token:
      access_expiry_seconds: 3600
      refresh_expiry_seconds: 1296000