spring:
  #  MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingdb?createDatabaseIfNotExist=true
    username: root
    password: Ranjan@2022
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true




  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingdb


  # SMTP Configuration
  mail:
    host: smtp.gmail.com
    username: ${mail.username}
    password: ${mail.pwd}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true